[features]
resolution = true
skip-lint = false

[programs.localnet]
sss2_hook = "FSkkSmrThcLpU9Uybrn4xcpbQKswUJn7KvoUQBsLPExD"

[programs.devnet]
sss2_hook = "FSkkSmrThcLpU9Uybrn4xcpbQKswUJn7KvoUQBsLPExD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"

[toolchain]
anchor_version = "0.30.1"
